### ISSUE TITLE
US02.01.01  Claims are listed with date, destinations, status, tags and totals

### ISSUE THREAD

**Issue by blainelewis1** [CMPUT301W15T10/301-Project#14]
As a claimant, I want to list all my expense claims, showing for each claim: the starting date of travel, the destination(s) of travel, the claim status, tags, and total currency amounts.

**Comment by Diusrex** [comment]
Start, status, and tags are displayed.

**Comment by Diusrex** [comment]
Also want to fix currency list in claimview

**Comment by Diusrex** [comment]
Currency is now listed properly.
