### ISSUE TITLE
Requirement Specifications (User Stories)

### ISSUE THREAD

**Issue by ChuckRozsa** [CMPUT301W15T10/301-Project#2]
Describe, using detailed textual use cases, the tasks for completing each type of entry. For each user story in the project description, add a reasonable set of verifying tests. For easier reference (such as in planning), number the use cases and user stories. This information will likely evolve and should be maintained up-to-date in your team wiki. A "surprise" change will be introduced after project part 2.

**Comment by Diusrex** [comment]
The only use cases that we haven't finished are the ones for editing claims and expenses.

Will also want to get Alex to look over them just to make sure the general idea is correct.
