### ISSUE TITLE
US05.01.01 Expenses are listed and sorted by order of entry showing all details

### ISSUE THREAD

**Issue by blainelewis1** [CMPUT301W15T10/301-Project#27]
As a claimant, I want to list all the expense items for a claim, in order of entry, showing for each expense item: the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, and incompleteness indicator.

**Comment by Diusrex** [comment]
Any expenses belonging to a Claim will be displayed in the correct order.
