### ISSUE TITLE
User Interface and UI Mock-Ups

### ISSUE THREAD

**Issue by ChuckRozsa** [CMPUT301W15T10/301-Project#3]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, provide one storyboard sequence for a non-trivial but coherent scenario of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Enter this information in your team wiki.

**Comment by jbenson370** [comment]
I am going to try and get all of these done tomorrow as a first draft based on our use cases so far and what the four of us who met today discussed. From there I think everyone should provide me with feedback and then as a group we can decide on what changes I should make for our submitted version.

**Comment by jbenson370** [comment]
Okay I have completed the four main UI diagrams we should need. They are a bit blocky but we can clean up the look to make it a bit more slick while actually in Eclipse. I am going to be scanning them and adding the textual descriptions of what every button/view is responsible for and then tonight I can upload them for everyone's review.
