### ISSUE TITLE
Glossary and Info Sources 

### ISSUE THREAD

**Issue by ChuckRozsa** [CMPUT301W15T10/301-Project#5]
Define any special terminology in the application domain (i.e., not programming terms). Provide a list of useful informational references or links to related or competitive products. Enter this information in your team wiki. Please clearly LICENSE your project.

**Comment by EdmondChuiHW** [comment]
We should use Apache 2.0 as it is compatible with Android Open Source Project and a large number of Android libraries on GitHub.

**Comment by jbenson370** [comment]
If that works with everyone else I am fine with Apache 2.0. I trust Edmunds' judgement.
